<?php

namespace Database\Seeders;

use App\Models\Bird;
use App\Models\Category;
use Illuminate\Database\Seeder;

class BirdSeeder extends Seeder
{
    public function run(): void
    {
        $parrots    = Category::where('slug', 'parrots')->first();
        $finches    = Category::where('slug', 'finches')->first();
        $canaries   = Category::where('slug', 'canaries')->first();
        $cockatiels = Category::where('slug', 'cockatiels')->first();
        $exotic     = Category::where('slug', 'exotic-birds')->first();

        $birds = [
            [
                'category_id'    => $parrots->id,
                'name'           => 'Scarlet Macaw',
                'slug'           => 'scarlet-macaw',
                'subtitle'       => 'Vibrant South American Parrot',
                'description'    => 'The Scarlet Macaw is one of the most stunning birds in the world. Known for its brilliant red, yellow, and blue plumage, this highly intelligent parrot thrives with enrichment, social interaction, and a spacious habitat.',
                'price'          => 2499.00,
                'original_price' => 2999.00,
                'image'          => 'bird-1.png',
                'gallery'        => ['bird-1.png', 'bird-2.png', 'bird-3.png', 'bird-4.png'],
                'badge'          => 'Featured',
                'species'        => 'Ara macao',
                'age'            => '2 Years',
                'temperament'    => 'Playful & Vocal',
                'habitat'        => 'Requires a large cage (minimum 36"×48") with horizontal bars for climbing. Provide natural wood perches and foraging toys.',
                'nutrition'      => 'High-quality pellets (60%), fresh fruits and vegetables (30%), and limited seeds (10%). Avoid avocado and chocolate.',
                'social'         => 'Thrives with daily interaction. Does well with experienced bird owners. Can be territorial with other large parrots.',
                'wingspan_cm'    => 100,
                'color'          => 'red',
                'is_active'      => true,
                'featured'       => true,
                'stock'          => 3,
            ],
            [
                'category_id'    => $cockatiels->id,
                'name'           => 'Pearl Cockatiel',
                'slug'           => 'pearl-cockatiel',
                'subtitle'       => 'Gentle Crested Companion',
                'description'    => 'The Pearl Cockatiel is a gentle, affectionate bird ideal for families. Their distinctive spotted plumage and soft whistles make them one of the most beloved companion birds.',
                'price'          => 349.00,
                'original_price' => 399.00,
                'image'          => 'bird-2.png',
                'gallery'        => ['bird-2.png', 'bird-1.png', 'bird-3.png'],
                'badge'          => 'Popular',
                'species'        => 'Nymphicus hollandicus',
                'age'            => '8 Months',
                'temperament'    => 'Gentle & Affectionate',
                'habitat'        => 'Medium cage (24"×24") with horizontal bars. Provide a cuttlebone and mineral block.',
                'nutrition'      => 'Cockatiel seed mix, fresh leafy greens, and occasional fruit treats.',
                'social'         => 'Excellent family bird. Gets along well with other cockatiels. Enjoys shoulder time.',
                'wingspan_cm'    => 35,
                'color'          => 'yellow',
                'is_active'      => true,
                'featured'       => true,
                'stock'          => 8,
            ],
            [
                'category_id'    => $parrots->id,
                'name'           => 'African Grey',
                'slug'           => 'african-grey',
                'subtitle'       => 'The Einstein of Parrots',
                'description'    => 'Renowned for their extraordinary intelligence and impressive vocabulary, African Greys are considered the most cognitively advanced parrots. They form deep bonds with their guardians.',
                'price'          => 3299.00,
                'original_price' => null,
                'image'          => 'bird-3.png',
                'gallery'        => ['bird-3.png', 'bird-1.png', 'bird-4.png'],
                'badge'          => 'Rare',
                'species'        => 'Psittacus erithacus',
                'age'            => '3 Years',
                'temperament'    => 'Intelligent & Sensitive',
                'habitat'        => 'Large cage minimum 36"×48". Requires mental stimulation through puzzles and foraging toys daily.',
                'nutrition'      => 'Balanced pellet diet supplemented with calcium-rich foods. Fresh vegetables daily.',
                'social'         => 'Bonds deeply with one person. Needs consistent social interaction to prevent feather-plucking.',
                'wingspan_cm'    => 55,
                'color'          => 'gray',
                'is_active'      => true,
                'featured'       => true,
                'stock'          => 2,
            ],
            [
                'category_id'    => $canaries->id,
                'name'           => 'Red Factor Canary',
                'slug'           => 'red-factor-canary',
                'subtitle'       => 'Striking Songbird',
                'description'    => 'The Red Factor Canary is prized for its vivid orange-red plumage and beautiful melodic song. A low-maintenance companion perfect for beginners.',
                'price'          => 189.00,
                'original_price' => 229.00,
                'image'          => 'bird-4.png',
                'gallery'        => ['bird-4.png', 'bird-2.png'],
                'badge'          => 'New Arrival',
                'species'        => 'Serinus canaria domesticus',
                'age'            => '6 Months',
                'temperament'    => 'Independent & Musical',
                'habitat'        => 'Flight cage (30"×18") allowing free flying. Canaries need room to flutter.',
                'nutrition'      => 'Canary seed mix, egg food, and fresh greens. Provide cuttlebone for calcium.',
                'social'         => 'Best kept solo or in same-sex pairs. Males sing more when kept alone.',
                'wingspan_cm'    => 22,
                'color'          => 'red',
                'is_active'      => true,
                'featured'       => false,
                'stock'          => 12,
            ],
            [
                'category_id'    => $finches->id,
                'name'           => 'Gouldian Finch',
                'slug'           => 'gouldian-finch',
                'subtitle'       => 'Rainbow of the Aviary',
                'description'    => 'The Gouldian Finch is one of the most spectacularly coloured birds on the planet. Native to Australia, these social finches thrive in small flocks.',
                'price'          => 299.00,
                'original_price' => null,
                'image'          => 'bird-5.png',
                'gallery'        => ['bird-5.png', 'bird-4.png'],
                'badge'          => 'Exotic',
                'species'        => 'Erythrura gouldiae',
                'age'            => '1 Year',
                'temperament'    => 'Peaceful & Social',
                'habitat'        => 'Large flight aviary. Gouldians need space and warmth (minimum 20°C).',
                'nutrition'      => 'Mixed millets, seeding grasses, and a small amount of live food for breeding pairs.',
                'social'         => 'Thrives in groups of 4+. Keep with other peaceful finch species.',
                'wingspan_cm'    => 18,
                'color'          => 'green',
                'is_active'      => true,
                'featured'       => false,
                'stock'          => 6,
            ],
            [
                'category_id'    => $exotic->id,
                'name'           => 'Hyacinth Macaw',
                'slug'           => 'hyacinth-macaw',
                'subtitle'       => 'The Gentle Giant',
                'description'    => 'The largest flying parrot in the world. Its cobalt-blue plumage is breathtaking. The Hyacinth Macaw is surprisingly gentle and affectionate despite its size.',
                'price'          => 12999.00,
                'original_price' => null,
                'image'          => 'bird-6.png',
                'gallery'        => ['bird-6.png', 'bird-1.png', 'bird-3.png'],
                'badge'          => 'Premium',
                'species'        => 'Anodorhynchus hyacinthinus',
                'age'            => '4 Years',
                'temperament'    => 'Gentle & Majestic',
                'habitat'        => 'Extra-large stainless steel cage (minimum 60"×48"). Requires powder-coated or stainless steel bars — their beak can bend iron.',
                'nutrition'      => 'Palm nuts are the primary diet. Supplement with macadamia nuts, corn, and specific macaw pellets.',
                'social'         => 'Extremely bonded to their guardian. Needs minimum 4 hours of out-of-cage time daily.',
                'wingspan_cm'    => 150,
                'color'          => 'blue',
                'is_active'      => true,
                'featured'       => true,
                'stock'          => 1,
            ],
        ];

        $additionalBirds = [

            // ── Parrots ──────────────────────────────────────────────────────
            [
                'category_id'    => $parrots->id,
                'name'           => 'Blue-fronted Amazon',
                'slug'           => 'blue-fronted-amazon',
                'subtitle'       => 'South American Talking Parrot',
                'description'    => 'The Blue-fronted Amazon is one of the most popular talking parrots in the world. Recognised by the vivid blue patch on its forehead, this charismatic bird is known for its impressive vocal abilities and playful nature.',
                'price'          => 1899.00,
                'original_price' => 2200.00,
                'image'          => 'bird-1.png',
                'badge'          => 'Talking',
                'species'        => 'Amazona aestiva',
                'age'            => '2 Years',
                'temperament'    => 'Playful & Vocal',
                'habitat'        => 'Large cage (36"×36") with plenty of enrichment toys. Needs daily out-of-cage time.',
                'nutrition'      => 'High-quality pellets, fresh fruits, vegetables, and limited seeds.',
                'social'         => 'Bonds strongly with family members. Can be nippy during hormonal periods.',
                'wingspan_cm'    => 60,
                'color'          => 'green',
                'is_active'      => true,
                'featured'       => false,
                'stock'          => 4,
            ],
            [
                'category_id'    => $parrots->id,
                'name'           => 'Eclectus Parrot',
                'slug'           => 'eclectus-parrot',
                'subtitle'       => 'Nature\'s Most Colourful Dimorphic Bird',
                'description'    => 'The Eclectus is unique — males are brilliant emerald green, females are vivid scarlet and blue. Once thought to be different species, these intelligent birds are calm, gentle, and highly perceptive.',
                'price'          => 2799.00,
                'original_price' => null,
                'image'          => 'bird-2.png',
                'badge'          => 'Rare',
                'species'        => 'Eclectus roratus',
                'age'            => '3 Years',
                'temperament'    => 'Calm & Perceptive',
                'habitat'        => 'Tall cage (36"×24"×48") with vertical climbing space. Sensitive to synthetic materials.',
                'nutrition'      => 'High fruit diet — mangoes, figs, pomegranates. Supplement with pellets designed for Eclectus.',
                'social'         => 'Gentle with all family members. Sensitive to stress and environmental change.',
                'wingspan_cm'    => 65,
                'color'          => 'green',
                'is_active'      => true,
                'featured'       => true,
                'stock'          => 2,
            ],
            [
                'category_id'    => $parrots->id,
                'name'           => 'Sun Conure',
                'slug'           => 'sun-conure',
                'subtitle'       => 'The Living Sunset',
                'description'    => 'Dressed in golden-yellow, orange, and green, the Sun Conure is one of the most visually stunning small parrots. Loud, affectionate, and full of personality — they demand attention and give unconditional love in return.',
                'price'          => 799.00,
                'original_price' => 950.00,
                'image'          => 'bird-3.png',
                'badge'          => 'Popular',
                'species'        => 'Aratinga solstitialis',
                'age'            => '1 Year',
                'temperament'    => 'Energetic & Affectionate',
                'habitat'        => 'Roomy cage (24"×24"×30") with stainless steel bars. Provide foraging toys and swings.',
                'nutrition'      => 'Pellet-based diet (70%) supplemented with seasonal fruits and dark leafy greens.',
                'social'         => 'Thrives on attention. Best in households that can manage their vocal nature.',
                'wingspan_cm'    => 38,
                'color'          => 'yellow',
                'is_active'      => true,
                'featured'       => false,
                'stock'          => 5,
            ],
            [
                'category_id'    => $parrots->id,
                'name'           => 'Green-winged Macaw',
                'slug'           => 'green-winged-macaw',
                'subtitle'       => 'The Gentle Giant of Macaws',
                'description'    => 'Often called the "Gentle Giant," the Green-winged Macaw is the second largest macaw species. Despite their imposing size and powerful beak, they are renowned for their calm, loving temperament.',
                'price'          => 4500.00,
                'original_price' => 5200.00,
                'image'          => 'bird-4.png',
                'badge'          => 'Premium',
                'species'        => 'Ara chloropterus',
                'age'            => '4 Years',
                'temperament'    => 'Gentle & Affectionate',
                'habitat'        => 'Extra-large cage (48"×36"×60"). Provide hardwood perches and durable stainless steel toys.',
                'nutrition'      => 'Macaw-specific pellets, fresh corn, nuts, fruits, and leafy vegetables.',
                'social'         => 'Highly social. Forms strong pair bonds. Excellent with respectful children.',
                'wingspan_cm'    => 125,
                'color'          => 'red',
                'is_active'      => true,
                'featured'       => true,
                'stock'          => 2,
            ],

            // ── Finches ──────────────────────────────────────────────────────
            [
                'category_id'    => $finches->id,
                'name'           => 'Zebra Finch',
                'slug'           => 'zebra-finch',
                'subtitle'       => 'Lively Beginner-Friendly Finch',
                'description'    => 'The Zebra Finch is the most popular finch species worldwide. Hardy, easy to care for, and entertaining to watch, they are ideal for first-time bird keepers and experienced aviculturists alike.',
                'price'          => 49.00,
                'original_price' => null,
                'image'          => 'bird-5.png',
                'badge'          => 'Beginner Friendly',
                'species'        => 'Taeniopygia guttata',
                'age'            => '4 Months',
                'temperament'    => 'Active & Hardy',
                'habitat'        => 'Flight cage (24"×16"). Keep in pairs or small groups — they are highly social.',
                'nutrition'      => 'Mixed small millets, eggfood, and occasional greens. Fresh water daily.',
                'social'         => 'Must be kept in pairs at minimum. Thrives in small flocks.',
                'wingspan_cm'    => 14,
                'color'          => 'orange',
                'is_active'      => true,
                'featured'       => false,
                'stock'          => 20,
            ],
            [
                'category_id'    => $finches->id,
                'name'           => 'Owl Finch',
                'slug'           => 'owl-finch',
                'subtitle'       => 'The Masked Charmer',
                'description'    => 'Named for the bold black-and-white facial markings that resemble an owl\'s face, these small Australian finches are gentle, quiet, and beautifully marked. Perfect for a mixed finch aviary.',
                'price'          => 89.00,
                'original_price' => 110.00,
                'image'          => 'bird-6.png',
                'badge'          => 'Exotic',
                'species'        => 'Taeniopygia bichenovii',
                'age'            => '6 Months',
                'temperament'    => 'Gentle & Quiet',
                'habitat'        => 'Large flight cage or aviary. Provide dense planting or nesting material.',
                'nutrition'      => 'Mixed grass seeds, sprouted seeds, and small live insects when breeding.',
                'social'         => 'Peaceful with all finch species. Best in pairs or small groups.',
                'wingspan_cm'    => 15,
                'color'          => 'brown',
                'is_active'      => true,
                'featured'       => false,
                'stock'          => 10,
            ],
            [
                'category_id'    => $finches->id,
                'name'           => 'Star Finch',
                'slug'           => 'star-finch',
                'subtitle'       => 'Dotted Australian Gem',
                'description'    => 'The Star Finch, native to northern Australia, is named for the white star-like spots scattered across its chest and flanks. A delightful, peaceful aviary bird with a soft, melodic call.',
                'price'          => 79.00,
                'original_price' => null,
                'image'          => 'bird-1.png',
                'badge'          => null,
                'species'        => 'Neochmia ruficauda',
                'age'            => '8 Months',
                'temperament'    => 'Peaceful & Active',
                'habitat'        => 'Planted aviary with access to grass seeds. Prefers warmth — keep above 18°C.',
                'nutrition'      => 'Grass seeds, sprouted millets, and small insects for breeding stimulation.',
                'social'         => 'Very peaceful. Ideal mixed-aviary bird with waxbills and grass finches.',
                'wingspan_cm'    => 16,
                'color'          => 'red',
                'is_active'      => true,
                'featured'       => false,
                'stock'          => 8,
            ],
            [
                'category_id'    => $finches->id,
                'name'           => 'Society Finch',
                'slug'           => 'society-finch',
                'subtitle'       => 'The Foster Parent of the Finch World',
                'description'    => 'Society Finches are famed for their social nature and willingness to foster eggs and chicks of other finch species. Gentle, adaptable, and easy to breed — they are an aviculturist\'s best friend.',
                'price'          => 39.00,
                'original_price' => null,
                'image'          => 'bird-2.png',
                'badge'          => 'Beginner Friendly',
                'species'        => 'Lonchura striata domestica',
                'age'            => '5 Months',
                'temperament'    => 'Social & Adaptable',
                'habitat'        => 'Standard flight cage. Provide nesting boxes and nesting material.',
                'nutrition'      => 'Small millet mix, eggfood, and leafy greens.',
                'social'         => 'Extremely social — must be kept in groups. Ideal aviary companion.',
                'wingspan_cm'    => 13,
                'color'          => 'brown',
                'is_active'      => true,
                'featured'       => false,
                'stock'          => 15,
            ],

            // ── Canaries ─────────────────────────────────────────────────────
            [
                'category_id'    => $canaries->id,
                'name'           => 'Yorkshire Canary',
                'slug'           => 'yorkshire-canary',
                'subtitle'       => 'The Gentleman of the Canary World',
                'description'    => 'The Yorkshire Canary is one of the most impressive type canaries — tall, upright, and elegantly proportioned. Bred for shape rather than song, these birds carry themselves with remarkable poise.',
                'price'          => 249.00,
                'original_price' => 289.00,
                'image'          => 'bird-3.png',
                'badge'          => 'Show Bird',
                'species'        => 'Serinus canaria domesticus',
                'age'            => '1 Year',
                'temperament'    => 'Calm & Distinguished',
                'habitat'        => 'Tall cage to accommodate their upright posture. Minimum 24"×18"×30".',
                'nutrition'      => 'Canary seed blend, egg food supplement, and fresh greens three times per week.',
                'social'         => 'Best kept individually or in same-sex groups outside breeding season.',
                'wingspan_cm'    => 24,
                'color'          => 'yellow',
                'is_active'      => true,
                'featured'       => false,
                'stock'          => 6,
            ],
            [
                'category_id'    => $canaries->id,
                'name'           => 'Gloster Canary',
                'slug'           => 'gloster-canary',
                'subtitle'       => 'The Tiny Crested Crooner',
                'description'    => 'Compact and endearing, the Gloster Canary is one of the smallest canary breeds. The "Corona" variety sports a distinctive round crest. They are cheerful, active singers with big personalities.',
                'price'          => 179.00,
                'original_price' => null,
                'image'          => 'bird-4.png',
                'badge'          => 'New Arrival',
                'species'        => 'Serinus canaria domesticus',
                'age'            => '9 Months',
                'temperament'    => 'Cheerful & Active',
                'habitat'        => 'Standard cage (18"×18"). Provide perches of varying widths for foot health.',
                'nutrition'      => 'Quality canary seed mix with weekly eggfood and soft fresh foods.',
                'social'         => 'Can be housed in pairs. Males may fight during breeding season.',
                'wingspan_cm'    => 19,
                'color'          => 'yellow',
                'is_active'      => true,
                'featured'       => false,
                'stock'          => 9,
            ],
            [
                'category_id'    => $canaries->id,
                'name'           => 'Mosaic Canary',
                'slug'           => 'mosaic-canary',
                'subtitle'       => 'The Lipochrome Colour Wonder',
                'description'    => 'The Mosaic Canary is a colour canary selectively bred to display intense patches of pigmentation on the head, shoulders, and chest. Their striking two-toned appearance makes them prized among collectors.',
                'price'          => 219.00,
                'original_price' => 259.00,
                'image'          => 'bird-5.png',
                'badge'          => 'Collector\'s Choice',
                'species'        => 'Serinus canaria domesticus',
                'age'            => '1 Year',
                'temperament'    => 'Independent & Musical',
                'habitat'        => 'Flight cage (30"×18"). Natural light exposure enhances colour retention.',
                'nutrition'      => 'Colour-enhancing canary pellets, carotenoid-rich foods like carrot and red pepper.',
                'social'         => 'Best kept singly or in pairs. Males sing most prolifically when alone.',
                'wingspan_cm'    => 21,
                'color'          => 'orange',
                'is_active'      => true,
                'featured'       => false,
                'stock'          => 7,
            ],

            // ── Cockatiels ───────────────────────────────────────────────────
            [
                'category_id'    => $cockatiels->id,
                'name'           => 'Lutino Cockatiel',
                'slug'           => 'lutino-cockatiel',
                'subtitle'       => 'Golden Crested Beauty',
                'description'    => 'The Lutino Cockatiel is a white-to-pale-yellow mutation with vivid orange cheek patches and red eyes. One of the most beloved cockatiel mutations, they are gentle, easy to tame, and enthusiastic whistlers.',
                'price'          => 299.00,
                'original_price' => 349.00,
                'image'          => 'bird-6.png',
                'badge'          => 'Popular',
                'species'        => 'Nymphicus hollandicus',
                'age'            => '7 Months',
                'temperament'    => 'Gentle & Affectionate',
                'habitat'        => 'Standard cage (24"×18"×24") with horizontal bars. Provide calcium supplements.',
                'nutrition'      => 'Cockatiel seed mix, pellets, fresh greens, and occasional millet spray.',
                'social'         => 'Highly social. Thrives with daily interaction and whistle training.',
                'wingspan_cm'    => 33,
                'color'          => 'yellow',
                'is_active'      => true,
                'featured'       => false,
                'stock'          => 10,
            ],
            [
                'category_id'    => $cockatiels->id,
                'name'           => 'Pied Cockatiel',
                'slug'           => 'pied-cockatiel',
                'subtitle'       => 'Patchy-Feathered Charmer',
                'description'    => 'The Pied Cockatiel features irregular patches of yellow and white across a grey body, creating a unique pattern on every individual bird. No two pieds look alike, making each one a one-of-a-kind companion.',
                'price'          => 279.00,
                'original_price' => null,
                'image'          => 'bird-1.png',
                'badge'          => null,
                'species'        => 'Nymphicus hollandicus',
                'age'            => '10 Months',
                'temperament'    => 'Curious & Sociable',
                'habitat'        => 'Medium cage (24"×18"). Provide foraging toys and cuttlebone.',
                'nutrition'      => 'Balanced seed and pellet mix with daily fresh vegetables.',
                'social'         => 'Very social. Gets along well with other cockatiels and calm household pets.',
                'wingspan_cm'    => 34,
                'color'          => 'yellow',
                'is_active'      => true,
                'featured'       => false,
                'stock'          => 7,
            ],
            [
                'category_id'    => $cockatiels->id,
                'name'           => 'Whiteface Cockatiel',
                'slug'           => 'whiteface-cockatiel',
                'subtitle'       => 'The Elegant Minimalist',
                'description'    => 'The Whiteface Cockatiel lacks the characteristic yellow pigmentation and orange cheek patches, resulting in a strikingly clean grey-and-white plumage. Elegant in their simplicity and deeply affectionate.',
                'price'          => 319.00,
                'original_price' => 369.00,
                'image'          => 'bird-2.png',
                'badge'          => 'Rare Mutation',
                'species'        => 'Nymphicus hollandicus',
                'age'            => '8 Months',
                'temperament'    => 'Calm & Devoted',
                'habitat'        => 'Medium cage with multiple perch heights. Provide UV lighting for 4–6 hours daily.',
                'nutrition'      => 'Pellets (50%), seeds (30%), and fresh foods (20%). Avoid iceberg lettuce.',
                'social'         => 'Forms strong one-person bonds. Excellent for quiet households.',
                'wingspan_cm'    => 33,
                'color'          => 'white',
                'is_active'      => true,
                'featured'       => false,
                'stock'          => 5,
            ],
            [
                'category_id'    => $cockatiels->id,
                'name'           => 'Cinnamon Cockatiel',
                'slug'           => 'cinnamon-cockatiel',
                'subtitle'       => 'Warm-Toned Gentle Companion',
                'description'    => 'The Cinnamon Cockatiel carries a sex-linked mutation that replaces grey feathers with warm brown tones. Their soft cinnamon-brown and yellow colouring gives them a uniquely warm, autumn-like appearance.',
                'price'          => 289.00,
                'original_price' => null,
                'image'          => 'bird-3.png',
                'badge'          => null,
                'species'        => 'Nymphicus hollandicus',
                'age'            => '9 Months',
                'temperament'    => 'Gentle & Playful',
                'habitat'        => 'Standard cockatiel cage with natural wood perches and foraging opportunities.',
                'nutrition'      => 'Seed and pellet blend, fresh spinach, broccoli, and apple slices.',
                'social'         => 'Friendly with all family members. Adapts well to multi-bird households.',
                'wingspan_cm'    => 32,
                'color'          => 'brown',
                'is_active'      => true,
                'featured'       => false,
                'stock'          => 8,
            ],

            // ── Exotic Birds ─────────────────────────────────────────────────
            [
                'category_id'    => $exotic->id,
                'name'           => 'Rainbow Lorikeet',
                'slug'           => 'rainbow-lorikeet',
                'subtitle'       => 'Australia\'s Living Jewel',
                'description'    => 'The Rainbow Lorikeet is arguably the most colourful parrot in the world. Their vivid multi-coloured plumage, playful clowning, and specialist nectar diet make them a truly unique companion.',
                'price'          => 1299.00,
                'original_price' => 1499.00,
                'image'          => 'bird-4.png',
                'badge'          => 'Exotic',
                'species'        => 'Trichoglossus moluccanus',
                'age'            => '18 Months',
                'temperament'    => 'Playful & Energetic',
                'habitat'        => 'Large cage or aviary with enrichment. Tolerant of humidity — misting appreciated.',
                'nutrition'      => 'Commercial lorikeet nectar, fresh fruit (mango, grapes, melons), and blossoms.',
                'social'         => 'Highly active and social. Does well in bonded pairs. Very interactive with owners.',
                'wingspan_cm'    => 47,
                'color'          => 'green',
                'is_active'      => true,
                'featured'       => true,
                'stock'          => 3,
            ],
            [
                'category_id'    => $exotic->id,
                'name'           => 'Sulphur-crested Cockatoo',
                'slug'           => 'sulphur-crested-cockatoo',
                'subtitle'       => 'The Iconic White Showstopper',
                'description'    => 'One of the most recognisable birds in the world, the Sulphur-crested Cockatoo commands attention with its brilliant white plumage and vivid yellow crest. Loud, charismatic, and deeply bonded to their people.',
                'price'          => 3499.00,
                'original_price' => null,
                'image'          => 'bird-5.png',
                'badge'          => 'Premium',
                'species'        => 'Cacatua galerita',
                'age'            => '5 Years',
                'temperament'    => 'Bold & Demanding',
                'habitat'        => 'Large stainless steel cage (48"×36"×60"). Requires a dedicated bird room or aviary ideally.',
                'nutrition'      => 'Low-fat pellet diet, fresh vegetables, and very limited seeds and nuts.',
                'social'         => 'Extremely needy of attention. Prone to feather destruction without sufficient stimulation.',
                'wingspan_cm'    => 103,
                'color'          => 'white',
                'is_active'      => true,
                'featured'       => false,
                'stock'          => 2,
            ],
            [
                'category_id'    => $exotic->id,
                'name'           => 'Toco Toucan',
                'slug'           => 'toco-toucan',
                'subtitle'       => 'Icon of the Rainforest Canopy',
                'description'    => 'The Toco Toucan is the largest and most recognisable toucan species. Their enormous orange-yellow bill is a marvel of nature — lightweight yet strong. These curious, animated birds form deep bonds with devoted owners.',
                'price'          => 8999.00,
                'original_price' => null,
                'image'          => 'bird-6.png',
                'badge'          => 'Ultra Rare',
                'species'        => 'Ramphastos toco',
                'age'            => '2 Years',
                'temperament'    => 'Curious & Animated',
                'habitat'        => 'Very large aviary. Toucans need space to hop and toss food with their bill.',
                'nutrition'      => 'Low-iron fruit diet — papaya, mango, banana, blueberries. Avoid high-iron foods.',
                'social'         => 'Can bond closely with one keeper. Require extensive daily interaction and enrichment.',
                'wingspan_cm'    => 65,
                'color'          => 'black',
                'is_active'      => true,
                'featured'       => true,
                'stock'          => 1,
            ],
            [
                'category_id'    => $exotic->id,
                'name'           => 'Victoria Crowned Pigeon',
                'slug'           => 'victoria-crowned-pigeon',
                'subtitle'       => 'The Royal Ground Dweller',
                'description'    => 'The Victoria Crowned Pigeon is the world\'s largest living pigeon — the size of a turkey. Its magnificent blue-lace crest and deep maroon breast make it look as though it was dressed by royalty.',
                'price'          => 6500.00,
                'original_price' => 7200.00,
                'image'          => 'bird-1.png',
                'badge'          => 'Ultra Rare',
                'species'        => 'Goura victoria',
                'age'            => '3 Years',
                'temperament'    => 'Regal & Calm',
                'habitat'        => 'Large ground-level aviary with soft substrate and sheltered nesting areas.',
                'nutrition'      => 'Grain, seeds, small berries, worms, and occasional insects.',
                'social'         => 'Gentle and trusting when hand-reared. Best kept in bonded pairs.',
                'wingspan_cm'    => 80,
                'color'          => 'blue',
                'is_active'      => true,
                'featured'       => true,
                'stock'          => 1,
            ],
        ];

        foreach (array_merge($birds, $additionalBirds) as $bird) {
            Bird::firstOrCreate(['slug' => $bird['slug']], $bird);
        }
    }
}
